#!/usr/bin/env python3

import argparse
import json
import re
import matplotlib
import matplotlib.pyplot as plt
import os

def main(args):
  with open(args.input, 'r') as f:
    raw = f.read()
  
  raw = json.loads(raw)

  headers = raw['meta']['format']['headers']
  units = raw['meta']['format']['units']
  data = raw['entries']

  elapsed = [e[0] for e in data]
  current = [e[1] for e in data]
  voltage = [e[2] for e in data]
  power = [e[3] for e in data]


  board = os.path.dirname(args.input).split('/')[1]
  mode = raw['meta']['config']['mode']
  value = raw['meta']['config']['value']

  leg = [(e[0] + ' (' + e[1] + ')') for e in zip(headers, units)]

  # plot the finished data
  fig, ax = plt.subplots()
  ax.plot(elapsed, current)
  ax.plot(elapsed, voltage)
  ax.plot(elapsed, power)
  ax.legend(leg[1:])
  ax.set_title(board + ' constant ' + mode + ' ' + str(value) + 'A')
  ax.set_xlabel(leg[0])

  dir = os.path.dirname(os.path.abspath(args.input))
  base = os.path.basename(args.input).split('.')[0]
  print(dir)

  fig.savefig(os.path.join(dir, base + '_plot.png'))



# when run as the main script:
if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Parallel Network Ping Utility')

  parser.add_argument('input', help='input datafile (generated by test.py)')

  args = parser.parse_args()
  main(args)
